#!/usr/bin/env python3
# /// script
# requires-python = ">=3.13,<=3.14"
# dependencies = []
# ///

"""Entrypoint for convenience to run without installing as a package."""

import sys
from pathlib import Path

package_source_path = Path(__file__).resolve().parent / 'src'
sys.path.insert(0, str(package_source_path))

import atpg_toolkit.cli  # noqa: E402

if __name__ == '__main__':
    atpg_toolkit.cli.main()
