#!/usr/bin/env python3
"""Entrypoint for convenience to run without installing."""

import sys
from pathlib import Path

package_source_path = Path(__file__).resolve().parent / 'src'
sys.path.insert(0, str(package_source_path))

import atpg_toolkit.cli

if __name__ == '__main__':
    atpg_toolkit.cli.main()
