line-length        = 120
target-version     = "py313"
format.quote-style = "single"


[lint]
  extend-select = [
    "B",    # bugbear
    "C4",   # flake8-comprehensions
    "D4",   # https://docs.astral.sh/ruff/rules/#pydocstyle-d
    "E",    # pycodestyle (error)
    "F",    # pyflakes
    "I",    # https://docs.astral.sh/ruff/rules/#isort-i
    "LOG",  # https://docs.astral.sh/ruff/rules/#flake8-logging-log,
    "N",    # https://docs.astral.sh/ruff/rules/#pep8-naming-n
    "PERF", # https://docs.astral.sh/ruff/rules/#perflint-perf
    "PGH",  # pygrep-hooks
    "PIE",  # flake8-pie
    "PYI",  # flake8-pyi
    "RSE",  # https://docs.astral.sh/ruff/rules/#flake8-raise-rse
    "RUF",  # https://docs.astral.sh/ruff/rules/#ruff-specific-rules-ruf
    "SIM",  # flake8-simplify
    "TCH",  # https://docs.astral.sh/ruff/rules/#flake8-type-checking-tch
    "UP",   # https://docs.astral.sh/ruff/rules/#pyupgrade-up
  ]
  fixable = ["ALL"]

  [lint.isort]
    required-imports = ["from __future__ import annotations"]

  [lint.per-file-ignores]
    "__*__.py"       = ["I002"]
    "./atpg-toolkit" = ["I002"]
    "tests/**"       = ["I002"]
