line-length = 120
target-version = "py313"
format.quote-style = "single"
lint.extend-select = [
  "UP",   # https://docs.astral.sh/ruff/rules/#pyupgrade-up
  "PERF", # https://docs.astral.sh/ruff/rules/#perflint-perf
  "RSE",  # https://docs.astral.sh/ruff/rules/#flake8-raise-rse
  "RUF",  # https://docs.astral.sh/ruff/rules/#ruff-specific-rules-ruf
  "TCH",  # https://docs.astral.sh/ruff/rules/#flake8-type-checking-tch
  "N",    # https://docs.astral.sh/ruff/rules/#pep8-naming-n
  "D4",   # https://docs.astral.sh/ruff/rules/#pydocstyle-d
  "I",    # https://docs.astral.sh/ruff/rules/#isort-i
  "LOG",  # https://docs.astral.sh/ruff/rules/#flake8-logging-log
]
lint.fixable = ["ALL"]
