on:
  push:
    branches:
      - master
    paths:
      - "**.py"

name: lint

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13", "3.14"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: astral-sh/setup-uv@v6
        id: setup-uv
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
      - run: uv run --only-dev --locked ruff check --output-format=github
      - run: uv run --only-dev --locked ruff format --check --diff
        if: ${{ !cancelled() && steps.setup-uv.outcome == 'success' }}
