on:
  push:
    paths:
      - "**.py"
      - "pyproject.toml"
      - "uv.lock"

name: test

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: astral-sh/setup-uv@v6
        with:
          python-version: "${{ matrix.python-version }}"
          enable-cache: true
      - run: uv run --locked pytest -v
